version: '3'
services:
  wordmove:
    depends_on: 
      - nginx      
    tty: true
    image: welaika/wordmove:php7
    restart: on-failure:5
    container_name: wpdocker_wordmove  # (+)
    volumes:
        - ./wordpress:/var/www/html
        - ~/.ssh:/root/.ssh      # (!)
